# Generated by Django 2.2.7 on 2019-11-25 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20191125_1605'),
        ('imagens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagens',
            name='pertence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.Paciente'),
        ),
    ]
