# Generated by Django 2.2.7 on 2019-11-25 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0002_imagens_pertence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='pertence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pacientes.Paciente'),
            preserve_default=False,
        ),
    ]
