# Generated by Django 2.2.7 on 2019-11-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da empresa', max_length=100)),
                ('email', models.EmailField(help_text='Email', max_length=254)),
                ('phone', models.CharField(help_text='Nome da empresa', max_length=100)),
                ('address', models.CharField(help_text='Nome da empresa', max_length=100)),
                ('CEP', models.CharField(help_text='Nome da empresa', max_length=100)),
                ('City', models.CharField(help_text='Nome da empresa', max_length=100)),
                ('State', models.CharField(help_text='Nome da empresa', max_length=100)),
            ],
        ),
    ]
