# Generated by Django 2.2.7 on 2019-11-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='CEP',
            field=models.CharField(help_text='CEP da empresa', max_length=100),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='City',
            field=models.CharField(help_text='Cidade da empresa', max_length=100),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='State',
            field=models.CharField(help_text='Estato da empresa', max_length=100),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='address',
            field=models.CharField(help_text='Rua da empresa', max_length=100),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='phone',
            field=models.CharField(help_text='Telefone da empresa', max_length=100),
        ),
    ]
