# Generated by Django 2.2.7 on 2019-12-01 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0003_clinica_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinica',
            name='user',
        ),
    ]
