# Generated by Django 2.2.7 on 2019-11-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Primeiro nome', max_length=100)),
                ('sobrenome', models.CharField(help_text='Sobrenome', max_length=100)),
                ('email', models.EmailField(help_text='Email', max_length=254)),
                ('phone', models.CharField(help_text='Telefone do Paciente', max_length=100)),
                ('address', models.CharField(help_text='Rua', max_length=100)),
                ('CEP', models.CharField(help_text='CEP', max_length=100)),
                ('City', models.CharField(help_text='Cidade', max_length=100)),
                ('State', models.CharField(help_text='Estato', max_length=100)),
            ],
        ),
    ]
