# Generated by Django 2.2.7 on 2019-11-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20191125_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='aniversario',
            field=models.CharField(default=1, help_text='Data de Aniversário', max_length=100),
            preserve_default=False,
        ),
    ]
