# Generated by Django 2.2.7 on 2019-11-27 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_paciente_aniversario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
