# Generated by Django 2.2.7 on 2019-12-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Famale', 'Famale')], max_length=20)),
                ('achado01', models.CharField(choices=[('restauração', 'restauracao'), ('coroa', 'coroa'), ('implante', 'implante')], max_length=20)),
            ],
        ),
    ]
