# Generated by Django 2.2.7 on 2019-12-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjDetectAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='img',
            field=models.ImageField(default=1, upload_to='detection'),
            preserve_default=False,
        ),
    ]
