# Generated by Django 2.2.7 on 2019-12-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjDetectAPI', '0002_detection_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='achado02',
            field=models.CharField(choices=[('restauração', 'restauracao'), ('coroa', 'coroa'), ('implante', 'implante'), ('canal', 'canal')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detection',
            name='achado03',
            field=models.CharField(choices=[('restauração', 'restauracao'), ('coroa', 'coroa'), ('implante', 'implante'), ('canal', 'canal')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detection',
            name='achado04',
            field=models.CharField(choices=[('restauração', 'restauracao'), ('coroa', 'coroa'), ('implante', 'implante'), ('canal', 'canal')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detection',
            name='achado05',
            field=models.CharField(choices=[('restauração', 'restauracao'), ('coroa', 'coroa'), ('implante', 'implante'), ('canal', 'canal')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detection',
            name='achado06',
            field=models.CharField(choices=[('restauração', 'restauracao'), ('coroa', 'coroa'), ('implante', 'implante'), ('canal', 'canal')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detection',
            name='achado07',
            field=models.CharField(choices=[('restauração', 'restauracao'), ('coroa', 'coroa'), ('implante', 'implante'), ('canal', 'canal')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detection',
            name='achado08',
            field=models.CharField(choices=[('restauração', 'restauracao'), ('coroa', 'coroa'), ('implante', 'implante'), ('canal', 'canal')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detection',
            name='achado09',
            field=models.CharField(choices=[('restauração', 'restauracao'), ('coroa', 'coroa'), ('implante', 'implante'), ('canal', 'canal')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detection',
            name='achado10',
            field=models.CharField(choices=[('restauração', 'restauracao'), ('coroa', 'coroa'), ('implante', 'implante'), ('canal', 'canal')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detection',
            name='achado11',
            field=models.CharField(choices=[('restauração', 'restauracao'), ('coroa', 'coroa'), ('implante', 'implante'), ('canal', 'canal')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detection',
            name='achado12',
            field=models.CharField(choices=[('restauração', 'restauracao'), ('coroa', 'coroa'), ('implante', 'implante'), ('canal', 'canal')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detection',
            name='achado13',
            field=models.CharField(choices=[('restauração', 'restauracao'), ('coroa', 'coroa'), ('implante', 'implante'), ('canal', 'canal')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detection',
            name='achado14',
            field=models.CharField(choices=[('restauração', 'restauracao'), ('coroa', 'coroa'), ('implante', 'implante'), ('canal', 'canal')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detection',
            name='achado15',
            field=models.CharField(choices=[('restauração', 'restauracao'), ('coroa', 'coroa'), ('implante', 'implante'), ('canal', 'canal')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detection',
            name='achado01',
            field=models.CharField(choices=[('restauração', 'restauracao'), ('coroa', 'coroa'), ('implante', 'implante'), ('canal', 'canal')], max_length=20),
        ),
    ]
